## Settings中添加如下Scerets，每个互助码间使用换行来分开
## SHARECODES_JDZZ 京东赚赚互助码
## SHARECODES_DDFACTORY 东东工厂互助码
## SHARECODES_JXFACTORY  京喜工厂互助码
## SHARECODES_BEAN  种豆得豆互助码
## SHARECODES_FARM  京东农场互助码
## SHARECODES_PET  京东萌宠互助码

name: 互助码自动上车

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1,10,20 * *'
  # watch:
  #   types: started
  repository_dispatch:
    types: create_sharecodes
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: 'main'
      - name: 提交互助码
        run: |
          chmod +x create_sharecodes.sh
          ./create_sharecodes.sh
        env:
          ShareCodesJDZZ: ${{ secrets.SHARECODES_JDZZ }}
          ShareCodesDdfactory: ${{ secrets.SHARECODES_DDFACTORY }}
          ShareCodesJxfactory: ${{ secrets.SHARECODES_JXFACTORY }}
          ShareCodesBean: ${{ secrets.SHARECODES_BEAN }}
          ShareCodesFarm: ${{ secrets.SHARECODES_FARM }}
          ShareCodesPet: ${{ secrets.SHARECODES_PET }}
          SCKEY: ${{ secrets.SCKEY }}
