 
name: 修改jdCookie.js
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "gitee"
jobs:
  fix-jdCookie:
    env:
      PAT: ${{ secrets.PAT }}      
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: gitee
    - name: '运行 【修改jdCookie】'
      run: |
             sed -i '/\\x47\\x49\\x54\\x48\\x55\\x42/d' jdCookie.js

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply fix-jdCookie changes
        branch: gitee
        file_pattern: jdCookie.js
