
name: 集汪汪卡瓜分百万红包(2021.1.6结束)

on:
  workflow_dispatch:
  schedule:
    - cron: '15 0 * * *'
  # watch:
  #   types: started
  repository_dispatch:
    types: jd_jdh
    
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'lxk0301/jd_scripts'
          ref: 'master'
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: install npm
        run: npm install
      - name: '运行 【集汪汪卡瓜分百万红包】'
        run: |
             node jd_jdh.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JD_DEBUG: ${{ secrets.JD_DEBUG }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
